//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.DbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblFaculty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TblFaculty()
        {
            this.tb1Student = new HashSet<tb1Student>();
        }
    
        public int Id { get; set; }
        public string FacultyName { get; set; }
        public string Section { get; set; }
        public Nullable<int> DepartmentId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tb1Student> tb1Student { get; set; }
        public virtual TblDepartment TblDepartment { get; set; }
    }
}
